In [64]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import seaborn as sns

In [65]:
df=sns.load_dataset('tips')
encoder=OneHotEncoder()
enco_sex=encoder.fit_transform(df[['sex']]).toarray()
print(enco_sex)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 

In [66]:
enco_sex_df=pd.DataFrame(enco_sex,columns=encoder.get_feature_names_out())
enco_sex_df

sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [68]:
print(df)
df.drop('sex',axis=1,inplace=True)
encoded_df=pd.concat([df,enco_sex_df],axis=1)
encoded_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]


total_bill   tip smoker   day    time  size  sex_Female  sex_Male
0         16.99  1.01     No   Sun  Dinner     2         1.0       0.0
1         10.34  1.66     No   Sun  Dinner     3         0.0       1.0
2         21.01  3.50     No   Sun  Dinner     3         0.0       1.0
3         23.68  3.31     No   Sun  Dinner     2         0.0       1.0
4         24.59  3.61     No   Sun  Dinner     4         1.0       0.0
..          ...   ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92     No   Sat  Dinner     3         0.0       1.0
240       27.18  2.00    Yes   Sat  Dinner     2         1.0       0.0
241       22.67  2.00    Yes   Sat  Dinner     2         0.0       1.0
242       17.82  1.75     No   Sat  Dinner     2         0.0       1.0
243       18.78  3.00     No  Thur  Dinner     2         1.0       0.0

[244 rows x 8 columns]

In [69]:
enco_day=encoder.fit_transform(df[['day']]).toarray()
enco_day

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],


In [70]:
enco_day_df=pd.DataFrame(enco_day,columns=encoder.get_feature_names_out())
enco_day_df

day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [71]:
encoded_df.drop('day',axis=1,inplace=True)

In [72]:
encoded_df=pd.concat([encoded_df,enco_day_df],axis=1)
encoded_df

total_bill   tip smoker    time  ...  day_Fri  day_Sat  day_Sun  day_Thur
0         16.99  1.01     No  Dinner  ...      0.0      0.0      1.0       0.0
1         10.34  1.66     No  Dinner  ...      0.0      0.0      1.0       0.0
2         21.01  3.50     No  Dinner  ...      0.0      0.0      1.0       0.0
3         23.68  3.31     No  Dinner  ...      0.0      0.0      1.0       0.0
4         24.59  3.61     No  Dinner  ...      0.0      0.0      1.0       0.0
..          ...   ...    ...     ...  ...      ...      ...      ...       ...
239       29.03  5.92     No  Dinner  ...      0.0      1.0      0.0       0.0
240       27.18  2.00    Yes  Dinner  ...      0.0      1.0      0.0       0.0
241       22.67  2.00    Yes  Dinner  ...      0.0      1.0      0.0       0.0
242       17.82  1.75     No  Dinner  ...      0.0      1.0      0.0       0.0
243       18.78  3.00     No  Dinner  ...      0.0      0.0      0.0       1.0

[244 rows x 11 columns]

In [73]:
enco_smoker=encoder.fit_transform(df[['smoker']]).toarray()
enco_smoker

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.

In [74]:
enco_smoker_df=pd.DataFrame(enco_smoker,columns=encoder.get_feature_names_out())
print(enco_smoker_df)

     smoker_No  smoker_Yes
0          1.0         0.0
1          1.0         0.0
2          1.0         0.0
3          1.0         0.0
4          1.0         0.0
..         ...         ...
239        1.0         0.0
240        0.0         1.0
241        0.0         1.0
242        1.0         0.0
243        1.0         0.0

[244 rows x 2 columns]


In [76]:
encoded_df.drop('smoker',axis=1,inplace=True)
encoded_df

total_bill   tip    time  size  ...  day_Fri  day_Sat  day_Sun  day_Thur
0         16.99  1.01  Dinner     2  ...      0.0      0.0      1.0       0.0
1         10.34  1.66  Dinner     3  ...      0.0      0.0      1.0       0.0
2         21.01  3.50  Dinner     3  ...      0.0      0.0      1.0       0.0
3         23.68  3.31  Dinner     2  ...      0.0      0.0      1.0       0.0
4         24.59  3.61  Dinner     4  ...      0.0      0.0      1.0       0.0
..          ...   ...     ...   ...  ...      ...      ...      ...       ...
239       29.03  5.92  Dinner     3  ...      0.0      1.0      0.0       0.0
240       27.18  2.00  Dinner     2  ...      0.0      1.0      0.0       0.0
241       22.67  2.00  Dinner     2  ...      0.0      1.0      0.0       0.0
242       17.82  1.75  Dinner     2  ...      0.0      1.0      0.0       0.0
243       18.78  3.00  Dinner     2  ...      0.0      0.0      0.0       1.0

[244 rows x 10 columns]

In [78]:
encoded_df=pd.concat([encoded_df,enco_smoker_df],axis=1)
encoded_df

total_bill   tip    time  ...  smoker_Yes  smoker_No  smoker_Yes
0         16.99  1.01  Dinner  ...         0.0        1.0         0.0
1         10.34  1.66  Dinner  ...         0.0        1.0         0.0
2         21.01  3.50  Dinner  ...         0.0        1.0         0.0
3         23.68  3.31  Dinner  ...         0.0        1.0         0.0
4         24.59  3.61  Dinner  ...         0.0        1.0         0.0
..          ...   ...     ...  ...         ...        ...         ...
239       29.03  5.92  Dinner  ...         0.0        1.0         0.0
240       27.18  2.00  Dinner  ...         1.0        0.0         1.0
241       22.67  2.00  Dinner  ...         1.0        0.0         1.0
242       17.82  1.75  Dinner  ...         0.0        1.0         0.0
243       18.78  3.00  Dinner  ...         0.0        1.0         0.0

[244 rows x 14 columns]